updated t2-push

diff --git a/scripts/t2-push b/scripts/t2-push
--- a/scripts/t2-push
+++ b/scripts/t2-push
@@ -1,43 +1,37 @@
-#!/usr/bin/env bash 
+#!/usr/bin/env bash
 
 T2_PROJECTS_DIR_PATH="$T2_HOME/projects"
 
 # exit script if running script from outside $T2_HOME/projects/*
-if [[ $PWD != $T2_PROJECTS_DIR_PATH/** ]]
-then
-    echo "You must run this script from within a subdirectory inside $T2_PROJECTS"
-    exit 1
+if [[ $PWD != $T2_PROJECTS_DIR_PATH/** ]]; then
+  echo "You must run this script from within a subdirectory inside $T2_PROJECTS"
+  exit 1
 fi
 
-
-
 # if ag-grid.config.sh file missing -> exit
-if [[ ! -f ag-grid.config.sh ]]
-then
-    echo "ag-grid.config.sh file is missing"
-    exit 1
+if [[ ! -f ag-grid.config.sh ]]; then
+  echo "ag-grid.config.sh file is missing"
+  exit 1
 fi
 
 # import FRAMEWORK, TICKET and DOCS_IMPORTED variables
 source "./ag-grid.config.sh"
 
 # optional commit message
-if [ $# -eq 0 ]
-  then
-    COMMIT_MESSAGE="updated ticket $TICKET"
-  else 
-    COMMIT_MESSAGE=$1
+if [ $# -eq 0 ]; then
+  COMMIT_MESSAGE="updated ticket $TICKET"
+else
+  COMMIT_MESSAGE=$1
 fi
 
 cd $T2_HOME
-git add . && /
-git commit -m "$COMMIT_MESSAGE" && /
+git add .
+git commit -m "$COMMIT_MESSAGE"
 git push
-
 
 echo "======================================================"
 echo "LINK TO CODESANDBOX: https://codesandbox.io/s/github/ag-grid/examples/tree/main/projects/${TICKET}"
-# stackblitz isnt really working 
+# stackblitz isnt really working
 # echo "LINK TO STACKBLITZ: https://stackblitz.com/github/ag-grid/examples/tree/main/projects/${TICKET}"
 echo "======================================================"
 
